### PR TITLE
Add the St unit

### LINKED ISSUE #48: Unit 'St' is not valid for quantity type 'volume per time per length'.
* Barril version: 1.10.0
* Python version: 3.6.7
* Operating System: Ubuntu 20.10

### Description

- `St` (Stokes) is one of the basic unit used by the kinematic viscosity magnitude. 
- Barril supports `cSt` (a variant of Stoke), but doesn't recognize the central unit. 

### What I Did

The following error is raised when I try to add a category with the `St` unit into the unit database.

```
E   ValueError: unit 'St' is not valid for quantity type 'volume per time per length'.
E   Quantity units: ['Mcf/d.ft', 'Mm3/d.m', 'Mm3/h.m', 'bbl/d.ft', 'cSt', 'cm2/s', 'ft2/d', 'ft2/h', 'ft2/s', 'galUK/hr.ft', 'galUK/hr.in', 'galUK/min.ft', 'galUS/hr.ft', 'galUS/hr.in', 'galUS/min.ft', 'in2/s', 'm2/d', 'm2/h', 'm2/s', 'm3/d.m', 'm3/h.m', 'm3/s.ft', 'm3/s.m', 'mm2/s']
```

### PR DESCRIPTION
**Pull request by matheuscardhosoo**
Fix #48

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]

**Comment by tigarmo** [comment]
@nicoddemus do you think we can update the contributing notes on this PR?

**Comment by nicoddemus** [comment]
@tigarmo you mean adding instructions on how to include new units?

**Comment by matheuscardhosoo** [comment]
I commented with @tigarmo that the Contribution Guide (CONTRIBUTING.rst) informs to open a PR in Travis to run the version tests. So, he suggested updating this file indicating that we use Github Actions now. What do you mean?

**Comment by nicoddemus** [comment]
Ahh OK. Yeah we can update the PR, but shouldn't there any instructions on how the tests are run, because they are executed automatically (it was not the case here due to a configuration bug, which has been fixed already).

Originally I wondered if @tigarmo meant we should add step-by-step instructions on how to add new units to barril, as that is a common occurrance.

**Comment by tigarmo** [comment]
Yes I meant update the Travis reference to Github Actions, sorry for the confusion
although this:
> we should add step-by-step instructions on how to add new units to barril, as that is a common occurrence.

is a good idea ;) (not on this PR though)

**Review by tigarmo — APPROVED** [review]

**Pull request merged**
